test

diff --git a/.github/workflows/dockertests.yml b/.github/workflows/dockertests.yml
--- a/.github/workflows/dockertests.yml
+++ b/.github/workflows/dockertests.yml
@@ -77,65 +77,54 @@ jobs:
       USE_LZO: 1
 
   test:
-    name: test
-    runs-on: ubuntu-latest
-    container:
-      image: ubuntu:20.04
-    needs: [ buildimages ]
-    strategy:
-      matrix:
-        # GH Actions lack of complex types support for inputs.
-        # Workaround https://github.com/orgs/community/discussions/11692#discussioncomment-3187271
-        command: ${{ fromJSON(inputs.command-json-array) }}
-      # do not cancel all tests if one failed
-      fail-fast: false
-    steps:
-      - name: Install deps
-        run: |
-          apt-get update
-          apt-get install -y liblzo2-dev ca-certificates build-essential git cmake curl
-          mkdir -p /etc/apt/keyrings
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
-          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
-          apt-get update
-          apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin sudo
-
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-
-      - name: Set up Go 1.x
-        uses: actions/setup-go@v5
-        with:
-          go-version: ${{ env.GO_VERSION }}
-        id: go
-
-      - name: Get dependencies
-        run: |
-          go get -v -t -d ./...
-
-      # load docker images
-      - name: Load docker images
-        id: cache-images
-        uses: actions/cache@v4
-        with:
-          path: |
-            ${{ env.CACHE_FILE_DOCKER_PREFIX }}
-            ${{ env.CACHE_FILE_UBUNTU_18_04 }}
-            ${{ env.CACHE_FILE_UBUNTU_20_04 }}
-            ${{ env.CACHE_FILE_GOLANG }}
-          key: ${{ env.IMAGES_CACHE_KEY }}
-
-      - name: Fail if no cached images
-        if: steps.cache-images.outputs.cache-hit != 'true'
-        run: |
-          echo "Failed to fetch cached docker images. Will now exit..."
-          exit 1
-
-      - name: Run test
-        run: |
-          git config --global --add safe.directory ${GITHUB_WORKSPACE}
-          ${{ matrix.command }}
-    env:
-      USE_BROTLI: 1
-      USE_LIBSODIUM: 1
-      USE_LZO: 1
+        name: test
+        runs-on: ubuntu-latest
+        needs: [ buildimages ]
+        strategy:
+          matrix:
+            # GH Actions lack of complex types support for inputs.
+            # Workaround https://github.com/orgs/community/discussions/11692#discussioncomment-3187271
+            command: ${{ fromJSON(inputs.command-json-array) }}
+          # do not cancel all tests if one failed
+          fail-fast: false
+        steps:
+          - name: Install deps
+            run: sudo apt-get install liblzo2-dev
+    
+          - name: Check out code into the Go module directory
+            uses: actions/checkout@v4
+    
+          - name: Set up Go 1.x
+            uses: actions/setup-go@v5
+            with:
+              go-version: ${{ env.GO_VERSION }}
+            id: go
+    
+          - name: Get dependencies
+            run: |
+              go get -v -t -d ./...
+    
+          # load docker images
+          - name: Load docker images
+            id: cache-images
+            uses: actions/cache@v4
+            with:
+              path: |
+                ${{ env.CACHE_FILE_DOCKER_PREFIX }}
+                ${{ env.CACHE_FILE_UBUNTU_18_04 }}
+                ${{ env.CACHE_FILE_UBUNTU_20_04 }}
+                ${{ env.CACHE_FILE_GOLANG }}
+              key: ${{ env.IMAGES_CACHE_KEY }}
+    
+          - name: Fail if no cached images
+            if: steps.cache-images.outputs.cache-hit != 'true'
+            run: |
+              echo "Failed to fetch cached docker images. Will now exit..."
+              exit 1
+    
+          - name: Run test
+            run: ${{ matrix.command }}
+        env:
+          USE_BROTLI: 1
+          USE_LIBSODIUM: 1
+          USE_LZO: 1
